### PR TITLE
Add sof-v2.6.1 for Intel cAVS2.5 hardware

### PR DESCRIPTION
**Pull request by kv2019i**
Add binaries for Intel Tiger/Alder/Raptor Lake systems, including both community and intel-signed binaries.

Community binaries build identification 'sofbuildresult/585'.

Build ID for intel-signed is 12434582.

### CODE REVIEW

**Comment by kv2019i** [comment]
The community binaries have an incorrect git tag (correct commit built, but the build machine did not have the v2.6.1 tag when building and this is visible in the built binary). This causes the BATS failure.

**Comment by kv2019i** [comment]
Community binaries fixed, tests now pass.

**Comment by mengdonglin** [comment]
LGTM. Thanks!

**Comment by kv2019i** [comment]
V3: 
- two small fixes to the FW symlinks (one unndeed extra file deleted, one missing symlink added)

**Pull request merged**
