### PR TITLE
Sof v2.0

### PR DESCRIPTION
**Pull request by keqiaozhang**

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@keqiaozhang are we missing any files for some platforms ?

**Comment by keqiaozhang** [comment]
> @keqiaozhang are we missing any files for some platforms ?

Confirmed, no missing files.
Comparing with v1.9.3(total 209 files changed), we added 13 new tplg files and 2 symbolic links under v2.0.x.
```
sof -> sof-v2. 0
sof-tplg -> sof-tplg-v2.0
```
The number of files is consistent.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@marc-hb fyi

**Comment by keqiaozhang** [comment]
Since I cannot force push this branch, so I create a new PR:https://github.com/thesofproject/sof-bin/pull/71
What's changed:
1. Replaced the XTOS built `sof-apl.ri` in community folder with zephyr built firmware.
2. add the related ldc file `sof-apl.ldc`

**Comment by marc-hb** [comment]
> Since I don't have the permission to force push sof-v2.0 branch(Protected branch)

I see you forked sof-bin on github, I was about to recommend that. I don't think we need any sof-bin branch.

**Comment by keqiaozhang** [comment]
> > Since I don't have the permission to force push sof-v2.0 branch(Protected branch)
> 
> I see you forked sof-bin on github, I was about to recommend that. I don't think we need any sof-bin branch.

Just realized to use the forked repo.

**Pull request closed without merging**
