### PR TITLE
Add Intel SOF2.7.2 topology files

### PR DESCRIPTION
**Pull request by kv2019i**
Add new and modified topologies from 2.7.2 release:

v2.7.x/sof-ace-tplg-v2.7.2
├── sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1.tplg ├── sof-mtl-max98357a-rt5682-ssp2-ssp0.tplg
├── sof-mtl-max98357a-rt5682.tplg
├── sof-mtl-rt713-l0-rt1316-l12-rt1713-l3.tplg
└── sof-mtl-rt713-l0-rt1316-l12.tplg

Topology build identification "Build #1385 stable-v2.7"

### CODE REVIEW

**Comment by kv2019i** [comment]
@bardliao @mengdonglin  Can you confirm this looks correct? For some reason I cannot add any reviewers to the PR...

**Comment by marc-hb** [comment]
Permissions were too lax at the entire project level, everyone had "WRITE" (= direct push, no PR) permission with no way for any repo to restrict.

@plbossart tightened this. Specific repos can still be lax if they want but now they don't have to.

**Comment by mengdonglin** [comment]
@kv2019i @bardliao I manually built topology of v2.7.2, and found 3 tplg files diff:
sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1.tplg
sof-mtl-max98357a-rt5682-ssp2-ssp0.tplg 
sof-mtl-max98357a-rt5682-ssp2-ssp0.tplg

The other 2 sof-mtl-rt713-* tplg files are same.

**Review by bardliao — APPROVED** [review]
The md5sum are the same as those in the build server for the stable-v2.7 branch.

**Review by mengdonglin — APPROVED** [review]

**Comment by kv2019i** [comment]
Verified the tplgs locally as well and got matching files reproduced (using public SOF docker image e76281c53adb).

**Pull request merged**
