### PR TITLE
converged: add adsp_fw_builder binaries

### PR DESCRIPTION
**Pull request by bkokoszx**
This commit adds adsp_fw_builder binaries.
adsp_fw_builder is a DSP converged firmware
image creation tool used to create manifest.

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

**Comment by bkokoszx** [comment]
@lgirdwood @mwasko 
FYI

**Review by lgirdwood — CHANGES_REQUESTED** [review]
Can we create a new ```tools-external``` directory since the files are not yet open source and put these file there. We also need to add a licence for these binaries.

**Comment by dbaluta** [comment]
@bkokoszx can you add more context. What are these binaries used for. What is converged :)

**Comment by bkokoszx** [comment]
@lgirdwood 
I will crate new tools-external directory. Should we put licence under 
LICENCE. Intel file in root dir or create another file e.g. in tools-xternal
dir?

@dbaluta 
These binaries are used to create manifest for binaries mentioned by @mwasko
here: 
https://github.com/thesofproject/sof/pull/4214#discussion_r635851657

**Comment by lgirdwood** [comment]
> @lgirdwood
> I will crate new tools-external directory. Should we put licence under
> LICENCE. Intel file in root dir or create another file e.g. in tools-xternal
> dir?
> 

I think it's probably best to have a ```LICENCE.adsp_fw_builder```, this keeps it simple for everyone to understand. We should also include these files in the ```make install``` rule too.

**Comment by bkokoszx** [comment]
@lgirdwood @mwasko 
I've changed folder to tools-external and added licence under LICENCE.adsp_fw_builder. 

@lgirdwood 
Is there a specific location where those binaries should be placed after make install?

**Comment by lgirdwood** [comment]
> @lgirdwood @mwasko
> I've changed folder to tools-external and added licence under LICENCE.adsp_fw_builder.
> 
> @lgirdwood
> Is there a specific location where those binaries should be placed after make install?

Probably ${PREFIX}/bin
@marc-hb I'm assuming this is still correct for installation today ?

**Review by marc-hb — CHANGES_REQUESTED** [review]
Wrong repo: sof-bin is not a repo for firmware build time dependencies. This would add a build time dependency on sof-bin, every developer and CI would now have to download it. No one does right now.

Either make these binaries part of https://github.com/thesofproject/sof/pull/4214 or add a new git submodule of sof.

> Is there a specific location where those binaries should be placed after make install?

Not sure which "make install" you're referring to. This seems to do nothing:
```
./scripts/xtensa-build-all.sh tgl
make -C build_gcc_tgl install # does nothing
```

**Comment by marc-hb** [comment]
> I agree that loadable modules build dependency on sof-bin will be cumbersome for developers and for CI but so will be a new git submodule of sof.

sof source has  hard dependencies on some git submodules already, so adding a new one will make very little difference / inconvenience (this is from someone who really dislikes submodules)

> If we want to address that we would have to agree to put the build related binaries in sof main repository - which I vote for.

The problem is that git performance is horrible with binaries and once they've been added to the git history they _cannot be taken back_ (no one cares about sof-bin or linux-firmware performance).

Another problem with having everything in the same repo is license confusion.

The standard and most popular solution to this problem is git LFS. LFS logic and user interface is vaguely similar to submodules but simpler to use and unlike submodules LFS is designed for binaries. Only URLs are added to the main git history, not the binaries themselves. Only one version is downloaded at a time and it's optional. I used LFS with gitlab in the past and it worked great. Github has first class support for LFS too https://docs.github.com/en/github/managing-large-files/versioning-large-files/configuring-git-large-file-storage

- If this is temporary (less than a few months) then a new git submodule is the least effort and disruption for CI and developers.
- If this is going to last a bit longer then git LFS is the best option.

> @marc-hb these binaries will have to be a part of FW release packages (on sof-bin) anyway, the same as tools like sof-logger currently are. The reason for that is to have complete package with compatible tools for 3rd party FW module/library build & integration.

sof-bin is not an SDK for 3rd party build and integration, never has been. It's only a place for final `/lib/firmware/` releases and not much else. Linux distributions avoid closed-source as much as possible for obvious security reasons and we have not found yet a distro downloading sof-logger from sof-bin, if needed (most likely not) I guess they just compile it from source. Compiling from source  also makes sure there's no "ABI" incompatibility issue, very common on Linux: https://stackoverflow.com/questions/4492799/undefined-reference-to-stack-chk-fail
https://stackoverflow.com/questions/11682748/is-clang-abi-same-as-g
etc.

With hindsight using a git repo for any kind of release with binaries was a mistake. A future SDK release should use https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository or anything else actually designed for binary releases. Example: https://github.com/zephyrproject-rtos/meta-zephyr-sdk/releases

**Comment by mwasko** [comment]
> @mwasko I think it may be simpler in the initial phase to place these binaries in a `sof_modules_staging` repo alongside our module code "as-is". This would then buy us time for upstreaming the tooling, whilst it was also available for general usage with minimal changes to the other tooling ?

That sounds reasonable, especially due to fact that the long term plan assume to open source the adsp_builder tools code which will resolve the problem.

**Comment by marc-hb** [comment]
I think I understand the need and I'm still pretty sure sof-bin.git is not the right place for this - neither from an "sof-bin" nor from a ".git" perspective.

**Pull request closed without merging**
