### PR TITLE
Add sof-v2.7-rc1 for Intel Meteor Lake hardware

### PR DESCRIPTION
**Pull request by kv2019i**
Add binaries for Intel Meteor Lake systems.

Community binaries build identification "#1016 stable-v2.7".

### CODE REVIEW

**Review by mengdonglin — APPROVED** [review]

**Comment by mengdonglin** [comment]
@kv2019i  Do we still need `sof-logger` in `tools-v2.7-rc1`?  As we usually use mtrace-reader.py to get the FW logging from memory.

**Comment by kv2019i** [comment]
Ack @mengdonglin , we can drop sof-logger. I was thinking we need it for older IPC3 binaries, but hmm, for those we'll get sof-logger from the v2.2.x folder (need to check this works, having problems with the multi-version-tarball script now).

**Comment by marc-hb** [comment]
> but hmm, for those we'll get sof-logger from the v2.2.x folder 

the tarball_multi script will give you the last one from the last directory argument so you probably don't want one sof-logger in `v2.7/`. It should work but...

>  having problems with the multi-version-tarball script now).

Please try #135 and #136

**Comment by kv2019i** [comment]
@marc-hb Marked this as ready. I'd like to merge this, so we could do a full dry run and release a rc1 tarball of sof-bin-2023.09-rc1. Doing that without merging this first, does not sound good.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> @marc-hb Marked this as ready. I'd like to merge this, so we could do a full dry run and release a rc1 tarball of sof-bin-2023.09-rc1. Doing that without merging this first, does not sound good.

Lets do the dry run. Merging.

**Pull request merged**
