### PR TITLE
SOF v2.3

### PR DESCRIPTION
**Pull request by mengdonglin**
Add v2.3 firmware binaries for Intel Tiger Lake, Alder Lake, and Raptor Lake platforms. This is the first release using Zephyr as the RTOS on these 3 platforms:  https://github.com/thesofproject/sof/releases/tag/v2.3

Please note 
- v2.2.x is still the recommended stable release for Linux distributions. v2.3 is for community hobbyist to try Zephyr FW builds on TGL/ADL/RPL.
- Name prefix **sofz-** is used for v2.3 FW to avoid name conflict with v2.2.x FW using XTOS as the RTOS. 
- The v2.3 tarball will combine v2.2.x FW & topology binaries with v2.3 FW binaries. After installation, the default FW binaries are still v2.2.x. To use v2.3 FW, please set kernel parameter `fw_filename=sofz-<platform name>.ri`

### CODE REVIEW

**Comment by mengdonglin** [comment]
Still debugging the checksum difference between community-signed and Intel-signed FW binaries.

**Comment by mengdonglin** [comment]
@lgirdwood @marc-hb I think the PR is ready to merge.

The PR BATS check failure is caused by a known issue on Zephyr side: The devicetree dependencies in .__device_handles_pass2 section has the same content but maybe in different order in different builds. This 

This issue was fixed by commit [scripts: gen_handles: Sort the device handles](https://github.com/zephyrproject-rtos/zephyr/commit/f896fc2306) in Zephyr upstream. With the fix we can compare different builds.

**Comment by marc-hb** [comment]
> This issue was fixed by commit [scripts: gen_handles: Sort the device handles](https://github.com/zephyrproject-rtos/zephyr/commit/f896fc2306) in Zephyr upstream.

Great find.

Can we backport this to a new stable-v2.3 branch here? https://github.com/thesofproject/zephyr/branches

We may need one in the future anyway.

Then we can tag and release SOF v2.3.1 with it and make sure there's no mismatch.

**Comment by lgirdwood** [comment]
Since this is a device tree ordering issue (where the DT data has the same values) and we have validated the binaries with this DT ordering then I'm good to merge this PR @mengdonglin. We can do v2.3.1 if we have runtime issues and include the DT ordering update.

**Comment by mengdonglin** [comment]
@marc-hb I adjusted the BATS test to allow checksum difference for SOF v2.3 FW binaries. Now we can pass all PR checks. 

@lgirdwood I added one commit to this PR to adjust BATs test as Marc suggested. We're good to merge.

**Review by lgirdwood — APPROVED** [review]

**Comment by marc-hb** [comment]
These 2 lines in Zephyr should help:
- https://github.com/zephyrproject-rtos/zephyr/pull/51954

**Pull request merged**
