### PR TITLE
v2.2.2

### PR DESCRIPTION
**Pull request by mengdonglin**
**Updated for the latest version:**
v2.2.2 is to add support for Intel Raptor Lake (RPL) platform. ~~It's a full release with FW, topology and tool binaries for all released platforms.~~

RPL has the same community signed binaries as TGL, and same Intel-
signed binaries as ADL, because
- TGL/ADL/RPL share the same audio IP and community signature;
- ADL and RPL also share the same production signature, but different
  from TGL.

Create new folder sof-v2.2.2 and create new symbolic links for RPL.
They point to v2.2 TGL and ADL FW binaries.

sof-v2.2.2/
├── community
│   ├── sof-rpl.ri -> sof-tgl.ri
│   └── sof-rpl-s.ri -> sof-tgl-h.ri
├── intel-signed
│   ├── sof-rpl.ri -> sof-adl.ri
│   └── sof-rpl-s.ri -> sof-adl-s.ri
├── sof-rpl.ldc -> sof-tgl.ldc
├── sof-rpl.ri -> intel-signed/sof-rpl.ri
├── sof-rpl-s.ldc -> sof-tgl-h.ldc
└── sof-rpl-s.ri -> intel-signed/sof-rpl-s.ri

sof-v2.2.2 needs to be combined with sof-v2.2 to get FW binaries for
all Intel released platforms. All other Intel platforms can stay
with v2.2 FW binaries, because there are no FW source code or binary
updates from v2.2

The latest version of sof tools is v2.2
The latest version of topology is v2.2.1

**To generate a tar ball to include latest binaries of FW, tool and
topology binaries for all Intel released platforms, please combine
v2.2 FW binaries, v2.2 sof tools, v2.2.1 topology, and this v2.2.2 FW
updates for RPL**:

$ ./tarball_multi_releases.bash v2.2.x/sof-v2.2 v2.2.x/tools-v2.2 \
v2.2.x/sof-tplg-v2.2.1/ v2.2.x/sof-v2.2.2

The manifest file in the tar ball can show source version of each
file and symbolic link.

cc:
- #90

### CODE REVIEW

**Comment by mengdonglin** [comment]
@lgirdwood Can you help invite Mark @mrhpearson to this repo?   He will integrate sof-bin releases to Debian. I hope to add him as a reviewer for the release PRs. Thanks!

**Review by keqiaozhang — APPROVED** [review]
LGTM

**Review by perexg — APPROVED** [review]

**Comment by marc-hb** [comment]
> For firmware binaries, same as v2.2

This means version 2.2 will appear in logs, correct?

**Comment by mengdonglin** [comment]
> > For firmware binaries, same as v2.2
> 
> This means version 2.2 will appear in logs, correct?

@marc-hb.  Correct. FW will report version v2.2 to kernel driver after booting the DSP and so v2.2 will appear in dmesg. The FW binaries are built from SOF tag v2.2 (https://github.com/thesofproject/sof/releases/tag/v2.2), and we don't rebuild any FW binaries.

**Review by marc-hb — DISMISSED** [review]
In that case I don't think it's a good idea to duplicate so many files in git.

I just tested my new script (submitted in #91) that can combine multiple versions and I can create the same final tarball without so much duplication in git; only in the tarball.

Like this:

```
./tarball_multi_releases.bash v2.2.x/sof-v2.2 v2.2.x/tools-v2.2 \
         v2.2.x/sof-tplg-v2.2.2/  v2.2.x/sof-v2.2.2-with-new-stuff-only
```

`v2.2.x/sof-v2.2.2-with-new-stuff-only` does not exist yet, it would have to be submitted first and it should of course be named `v2.2.x/sof-v2.2.2`. It would 1% the size of this PR.

**Comment by marc-hb** [comment]
Also, `./tarball_multi_releases.bash` produces the same tarball except it includes a new `manifest.txt` file that shows what was the "real" release for each file.

**Comment by mengdonglin** [comment]
@marc-hb I'll only keep new FW symbolic links for RPL and try the latest #91

**Comment by mrhpearson** [comment]
Looks good to me - thanks!

**Comment by mengdonglin** [comment]
@marc-hb @mrhpearson @perexg @keqiaozhang I tried Marc's idea to reduce copies of identical FW, topology and tool binaries. It works well for me. So I updated the PR. Can you please give a review again?

Major changes:
New symbolic links are created for RPL. They point to v2.2 TGL and
ADL FW binaries. v2.2 TGL and ADL FW binaries (*.ri) and logging
dictionary files (*.ldc) are copied from sof-v2.2 to avoid broken
symbolic links.

sof-v2.2.2
├── community
│   ├── sof-rpl.ri -> sof-tgl.ri
│   ├── sof-rpl-s.ri -> sof-tgl-h.ri
│   ├── sof-tgl-h.ri
│   └── sof-tgl.ri
├── intel-signed
│   ├── sof-adl.ri
│   ├── sof-adl-s.ri
│   ├── sof-rpl.ri -> sof-adl.ri
│   └── sof-rpl-s.ri -> sof-adl-s.ri
├── sof-rpl.ldc -> sof-tgl.ldc
├── sof-rpl.ri -> intel-signed/sof-rpl.ri
├── sof-rpl-s.ldc -> sof-tgl-h.ldc
├── sof-rpl-s.ri -> intel-signed/sof-rpl-s.ri
├── sof-tgl-h.ldc
└── sof-tgl.ldc

All other Intel released platforms can stay with v2.2 FW binaries,
because there are no FW source code or binary updates from v2.2

The latest version of sof tools is v2.2.
The latest version of topology is v2.2.1

To combine v2.2 FW binaries, v2.2 sof tools, v2.2.1 topology, and
this v2.2.2 FW updates for RPL, please run

$ ./tarball_multi_releases.bash v2.2.x/sof-v2.2 v2.2.x/tools-v2.2 \
v2.2.x/sof-tplg-v2.2.1/ v2.2.x/sof-v2.2.2

A tar ball will be generated to include all the binaries with a
manifest file to show source version of each file and symbolic link.

**Comment by marc-hb** [comment]
Thanks again @mengdonglin for the instant testing, so much teamwork across timezones is exhilarating :-)

https://github.com/thesofproject/sof-bin/actions/runs/3061834845/jobs/4942097194 is failing because you're removing the `cavs-*.tplg` files - great to see the brand new tests detecting and reporting this:

```
 ✗ tarball_topologies_only 2.2.1
   (from function `test_tarball_topologies_only' in file tests/tests.bats, line 104,
    in test file tests/tests.bats, line 46)
     `test_tarball_topologies_only v2.2.x "$ver"' failed
   ~/SOF/sof-bin/testruns/run-XWhaJM ~/SOF/sof-bin
   + git archive -9 -o /home/mherber2/SOF/sof-bin/testruns/run-XWhaJM/sof-tplg-v2.2.1.tar.gz HEAD -- sof-tplg-v2.2.1
   Only in sof-bin/tests/extracted_refs//sof-tplg-v2.2.1: cavs-mixin-mixout-hda-2ch-cnl.tplg
   Only in sof-bin/tests/extracted_refs//sof-tplg-v2.2.1: cavs-mixin-mixout-hda-2ch-tgl.tplg
   Only in sof-bin/tests/extracted_refs//sof-tplg-v2.2.1: cavs-mixin-mixout-hda-4ch-cnl.tplg
   Only in sof-bin/tests/extracted_refs//sof-tplg-v2.2.1: cavs-mixin-mixout-hda-4ch-tgl.tplg
   Only in sof-bin/tests/extracted_refs//sof-tplg-v2.2.1: cavs-mixin-mixout-hda.tplg
   Only in sof-bin/tests/extracted_refs//sof-tplg-v2.2.1: cavs-passthrough-hdmi.tplg
   Only in sof-bin/tests/extracted_refs//sof-tplg-v2.2.1: cavs-sdw.tplg
   Only in sof-bin/tests/extracted_refs//sof-tplg-v2.2.1: cavs-tgl-nocodec.tplg
```

In general we should never remove files that have been released but there are always exceptions and this one makes sense to me.

You can very easily make this test pass again (TESTED!) if you rebase after my brand new #100 is merged.

**Comment by marc-hb** [comment]
> A tar ball will be generated to include all the binaries with a
manifest file to show source version of each file and symbolic link.

I downloaded this PR, ran @mengdonglin's command and here's a slightly shorten version of this manifest.txt found in the tarball. Note this is NOT the content of the tarball! This is the manifest.txt file inside it.

```
cat manifest.txt

sof-tplg-v2.2.1 ./sof-acp.tplg
sof-tplg-v2.2.1 ./sof-adl-cs35l41.tplg
sof-tplg-v2.2.1 ./sof-adl-max98357a-rt5682.tplg
sof-tplg-v2.2.1 ./sof-adl-max98357a-rt5682-2way.tplg
sof-tplg-v2.2.1 ./sof-adl-max98357a-rt5682-4ch.tplg
sof-tplg-v2.2.1 ./sof-adl-max98357a-rt5682-rtnr.tplg
sof-tplg-v2.2.1 ./sof-adl-max98357a-rt5682-waves.tplg
sof-tplg-v2.2.1 ./sof-adl-max98357a-rt5682-waves-2way.tplg
sof-tplg-v2.2.1 ./sof-adl-max98360a-nau8825.tplg
sof-tplg-v2.2.1 ./sof-adl-max98360a-rt5682.tplg
.
.
.
sof-tplg-v2.2.1 ./sof-tgl-rt715-rt711-rt1308-mono.tplg
sof-tplg-v2.2.1 ./sof-tgl-rt1011-rt5682.tplg
sof-tplg-v2.2.1 ./sof-tgl-rt5682-ssp0-max98373-ssp2.tplg
sof-tplg-v2.2.1 ./sof-tgl-rt5682-ssp0-max98373-ssp2-xperi.tplg
sof-tplg-v2.2.1 ./sof-tgl-sdw-max98373-rt5682.tplg
sof-tplg-v2.2.1 ./sof-whl-demux-rt5682.tplg
sof-tplg-v2.2.1 ./sof-whl-rt5682.tplg
sof-tplg-v2.2.1 ./sof-whl-rt5682-kwd.tplg
sof-v2.2        ./community/sof-apl.ri
sof-v2.2        ./community/sof-cnl.ri
sof-v2.2        ./community/sof-icl.ri
sof-v2.2        ./community/sof-jsl.ri
sof-v2.2        ./intel-signed/sof-apl.ri
sof-v2.2        ./intel-signed/sof-cnl.ri
sof-v2.2        ./intel-signed/sof-ehl.ri
sof-v2.2        ./intel-signed/sof-icl.ri
sof-v2.2        ./intel-signed/sof-jsl.ri
sof-v2.2        ./intel-signed/sof-tgl.ri
sof-v2.2        ./intel-signed/sof-tgl-h.ri
sof-v2.2        ./sof-apl.ldc
sof-v2.2        ./sof-bdw.ldc
sof-v2.2        ./sof-bdw.ri
sof-v2.2        ./sof-byt.ldc
sof-v2.2        ./sof-byt.ri
sof-v2.2        ./sof-cht.ldc
sof-v2.2        ./sof-cht.ri
sof-v2.2        ./sof-cnl.ldc
sof-v2.2        ./sof-icl.ldc
sof-v2.2        ./sof-jsl.ldc
sof-v2.2.2      ./community/sof-tgl.ri
sof-v2.2.2      ./community/sof-tgl-h.ri
sof-v2.2.2      ./intel-signed/sof-adl.ri
sof-v2.2.2      ./intel-signed/sof-adl-s.ri
sof-v2.2.2      ./sof-tgl.ldc
sof-v2.2.2      ./sof-tgl-h.ldc
tools-v2.2      ./sof-ctl
tools-v2.2      ./sof-logger
tools-v2.2      ./sof-probes

#   --- symbolic links ---

sof-v2.2        ./community/sof-adl-s.ri -> sof-tgl-h.ri
sof-v2.2        ./community/sof-adl.ri -> sof-tgl.ri
sof-v2.2        ./community/sof-cfl.ri -> sof-cnl.ri
sof-v2.2        ./community/sof-cml.ri -> sof-cnl.ri
sof-v2.2        ./community/sof-ehl.ri -> sof-tgl.ri
sof-v2.2        ./community/sof-glk.ri -> sof-apl.ri
sof-v2.2        ./intel-signed/sof-cfl.ri -> sof-cnl.ri
sof-v2.2        ./intel-signed/sof-cml.ri -> sof-cnl.ri
sof-v2.2        ./intel-signed/sof-glk.ri -> sof-apl.ri
sof-v2.2        ./sof-adl-s.ldc -> sof-tgl-h.ldc
sof-v2.2        ./sof-adl-s.ri -> intel-signed/sof-adl-s.ri
sof-v2.2        ./sof-adl.ldc -> sof-tgl.ldc
sof-v2.2        ./sof-adl.ri -> intel-signed/sof-adl.ri
sof-v2.2        ./sof-apl.ri -> intel-signed/sof-apl.ri
sof-v2.2        ./sof-cfl.ldc -> sof-cnl.ldc
sof-v2.2        ./sof-cfl.ri -> intel-signed/sof-cfl.ri
sof-v2.2        ./sof-cml.ldc -> sof-cnl.ldc
sof-v2.2        ./sof-cml.ri -> intel-signed/sof-cml.ri
sof-v2.2        ./sof-cnl.ri -> intel-signed/sof-cnl.ri
sof-v2.2        ./sof-ehl.ldc -> sof-tgl.ldc
sof-v2.2        ./sof-ehl.ri -> intel-signed/sof-ehl.ri
sof-v2.2        ./sof-glk.ldc -> sof-apl.ldc
sof-v2.2        ./sof-glk.ri -> intel-signed/sof-glk.ri
sof-v2.2        ./sof-icl.ri -> intel-signed/sof-icl.ri
sof-v2.2        ./sof-jsl.ri -> intel-signed/sof-jsl.ri
sof-v2.2        ./sof-tgl-h.ri -> intel-signed/sof-tgl-h.ri
sof-v2.2        ./sof-tgl.ri -> intel-signed/sof-tgl.ri
sof-v2.2.2      ./community/sof-rpl-s.ri -> sof-tgl-h.ri
sof-v2.2.2      ./community/sof-rpl.ri -> sof-tgl.ri
sof-v2.2.2      ./intel-signed/sof-rpl-s.ri -> sof-adl-s.ri
sof-v2.2.2      ./intel-signed/sof-rpl.ri -> sof-adl.ri
sof-v2.2.2      ./sof-rpl-s.ldc -> sof-tgl-h.ldc
sof-v2.2.2      ./sof-rpl-s.ri -> intel-signed/sof-rpl-s.ri
sof-v2.2.2      ./sof-rpl.ldc -> sof-tgl.ldc
sof-v2.2.2      ./sof-rpl.ri -> intel-signed/sof-rpl.ri

```

**Comment by marc-hb** [comment]
> . v2.2 TGL and ADL FW binaries (.ri) and logging dictionary files (.ldc) are copied from sof-v2.2 to avoid broken symbolic links.

This is confusing. I think I know why my new script forced you to do that and I just submitted a (TESTED!) one-line fix in brand new
- #101

**Comment by marc-hb** [comment]
Totally different topic: I think we should get rid of the `v2.2.x/sof[-tplg]` symbolic links because pointing them at v2.2.2 will NOT work with like @mrhpearson used to use them. So better fail _earlier than later_ in the Debian package script. Longer story in #90

**Review by marc-hb — CHANGES_REQUESTED** [review]
At least one of the things I just requested hopefully makes sense :-)

**Comment by mengdonglin** [comment]
@marc-hb @mrhpearson @perexg @keqiaozhang @lgirdwood I updated the PR to v3. Can you please review?

We also need Marc's PR #100 and #101 to be merged at first. #100 can fix PR check error. #101 can fix script complaining about broken symbolic links when generating the combined tar ball.

Major changes:
- Only create new symbolic links for RPL, but no longer copy v2.2 TGL and ADL FW binaries to sof-v2.2.2 folder.
```
    sof-v2.2.2/
    ├── community
    │   ├── sof-rpl.ri -> sof-tgl.ri
    │   └── sof-rpl-s.ri -> sof-tgl-h.ri
    ├── intel-signed
    │   ├── sof-rpl.ri -> sof-adl.ri
    │   └── sof-rpl-s.ri -> sof-adl-s.ri
    ├── sof-rpl.ldc -> sof-tgl.ldc
    ├── sof-rpl.ri -> intel-signed/sof-rpl.ri
    ├── sof-rpl-s.ldc -> sof-tgl-h.ldc
    └── sof-rpl-s.ri -> intel-signed/sof-rpl-s.ri
```
- Get rid of the v2.2.x/sof[-tplg] symbolic links as Marc suggested.

**Comment by marc-hb** [comment]
> We also need Marc's PR https://github.com/thesofproject/sof-bin/pull/100 and https://github.com/thesofproject/sof-bin/pull/101 to be merged at first. https://github.com/thesofproject/sof-bin/pull/100 can fix PR check error. https://github.com/thesofproject/sof-bin/pull/101 can fix script complaining about broken symbolic links when generating the combined tar ball.

Both were merged 30+ minutes ago

**Comment by mengdonglin** [comment]
> > We also need Marc's PR #100 and #101 to be merged at first. #100 can fix PR check error. #101 can fix script complaining about broken symbolic links when generating the combined tar ball.
> 
> Both were merged 30+ minutes ago. Please rebase and uncomment `rm cavs*.tplg` in `tests/tests.bat`

@marc-hb Rebased and uncomment `rm cavs*.tplg` in `tests/tests.bat`. PR test is green now. Thank you!

**Review by marc-hb — APPROVED** [review]
LGTM, @lgirdwood / @plbossart please review the RPL additions.

**Comment by mengdonglin** [comment]
@perexg @mrhpearson Can you please check if the latest version looks good to you? Thanks

**Comment by mrhpearson** [comment]
As I plan on moving to the tarballs, this probably isn't a big deal - but as I understand what was done it seemed a bit weird.

If you check the links - they are now all invalid as they point at files that aren't there. e.g.
```
$ ls -l v2.2.x/sof-v2.2.2
total 16
drwxr-xr-x. 1 banther banther 44 Sep 16 11:33 community
drwxr-xr-x. 1 banther banther 44 Sep 16 11:33 intel-signed
lrwxrwxrwx. 1 banther banther 11 Sep 16 11:33 sof-rpl.ldc -> sof-tgl.ldc
lrwxrwxrwx. 1 banther banther 23 Sep 16 11:33 sof-rpl.ri -> intel-signed/sof-rpl.ri
lrwxrwxrwx. 1 banther banther 13 Sep 16 11:33 sof-rpl-s.ldc -> sof-tgl-h.ldc
lrwxrwxrwx. 1 banther banther 25 Sep 16 11:33 sof-rpl-s.ri -> intel-signed/sof-rpl-s.ri

```
The files being linked to don't exist as they are really in v2.2. Shouldn't they link backwards to ../sof-v2.2/sof-tgl.ldc (for example).

Apologies if I'm missing something obvious (or I've managed to review the wrong thing)
Mark

**Comment by marc-hb** [comment]
> If you check the links - they are now all invalid as they point at files that aren't there

That's because they point at existing 2.2 files. This new 2.2.2 directory is just a small addition to 2.2, they will be merged together by `tarball_multi_releases.sh`. This avoids duplication in git.

See https://github.com/thesofproject/sof-bin/pull/98#issuecomment-1248517433

**Comment by mrhpearson** [comment]
OK - I think I get it. Still find it a little strange to be honest...but it will make more sense once I get the packaging side figured out

**Comment by vincentbernat** [comment]
Hey!
Just to be sure: when 2.2.2 is released, the tarball will be provided as an asset to the release? If yes, that's great.

**Comment by mengdonglin** [comment]
> Hey! Just to be sure: when 2.2.2 is released, the tarball will be provided as an asset to the release? If yes, that's great.

@vincentbernat Thanks for feedback! I think you will integrate SOF into Ubuntu, right? 
We can upload the tarball as an asset to the v2.2.2 release as we did for previous releases. This tarball will include all the latest FW, topology and sof tool binaries, generated by  
`$ ./tarball_multi_releases.bash v2.2.x/sof-v2.2 v2.2.x/tools-v2.2 v2.2.x/sof-tplg-v2.2.1/ v2.2.x/sof-v2.2.2` 

@perexg Are you also good with this plan?

**Comment by vincentbernat** [comment]
I just help @mrhpearson on the Debian packaging. @LocutusOfBorg  is the last one who did an upload for Ubuntu, based on the Debian package.

**Comment by mengdonglin** [comment]
> Just to be extra sure: will tarballs for future release always contain both sof-tplg and sof directories, unlike what has been done for 2.2 and 2.2.1?

@vincentbernat Yes, the tarball will always contain both sof-tplg and sof directories for future releases. We'll clarify how the tarball is generated in the release notes. 

If users are not satisfied with the default tarball, they can use the scripts to generate their own tarball(s).

**Comment by LocutusOfBorg** [comment]
Hello, in Ubuntu we have a delta for this package
    - Add a new tplg file to v2.0.x sof-adl-rt711-l2-rt1316-l01.tplg
   
why aren't such files upstream?
http://launchpadlibrarian.net/597502647/firmware-sof_2.0-1ubuntu2_2.0-1ubuntu3.diff.gz

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1966841

**Comment by LocutusOfBorg** [comment]
or aren't them needed anymore with new release?

**Comment by plbossart** [comment]
Looks like a miss @LocutusOfBorg, this file is part of the mainline and was likely missed in the backport to 2.2. It's definitively needed by some Dell SKUs without local microphones. From the CMakeLists.txt:

````
	"sof-icl-rt711-rt1308-rt715-hdmi\;sof-adl-rt711-l2-rt1316-l01\;-DPLATFORM=adl\;-DUAJ_LINK=2\;-DAMP_1_LINK=0\;-DAMP_2_LINK=1\;-DEXT_AMP_REF\;-DNO_LOCAL_MIC"
````

@mengdonglin @marc-hb FYI.

**Comment by plbossart** [comment]
Actually this file is correctly shown in the backported v2.2.2, so not sure how it can be missing from the release binary? I also see it in 2.2.1,

**Comment by LocutusOfBorg** [comment]
as long as it works, its good for me :)

**Comment by lgirdwood** [comment]
@mengdonglin @marc-hb still draft - are we blocking on #102 ?

**Comment by mengdonglin** [comment]
> @mengdonglin @marc-hb still draft - are we blocking on #102 ?
@lgirdwood @marc-hb tested with PR #102.  I rebased this PR with latest main.

**Comment by marc-hb** [comment]
> Marc plans to add a couple of tests for install.sh tomorrow. We can wait for these tests 

No need to wait for these tests.

**Comment by mengdonglin** [comment]
> > Marc plans to add a couple of tests for install.sh tomorrow. We can wait for these tests
> 
> No need to wait for these tests.

@marc-hb okay. Then I'll apply tag v2.2.2 to sof-bin and upload tarball once this PR gets merged.
@lgirdwood  Can you please merge this PR?

**Comment by mengdonglin** [comment]
@lgirdwood  Thank you!

@marc-hb @mrhpearson @vincentbernat @LocutusOfBorg @perexg v2.2.2 is done and tarball is uploaded: https://github.com/thesofproject/sof-bin/releases/tag/v2.2.2 

Please file a bug if you see any issues with this release. Thank you!

**Comment by perexg** [comment]
@mengdonglin : The binary file is not a part of the assets like in the previous releases. The URL https://github.com/thesofproject/sof-bin/releases/download/v2.2.2/sof-bin-v2.2.2.tar.gz does not work (comparing to https://github.com/thesofproject/sof-bin/releases/download/v2.1.1/sof-bin-v2.1.1.tar.gz).

**Comment by marc-hb** [comment]
Thx @perexg , I'm looking into that. In the mean time could try the https://github.com/thesofproject/sof-bin/files/9632845/sof-bin-v2.2.2.tar.gz link that can be found slightly above in the page?

**Comment by perexg** [comment]
The tar ball works (seem ok locally), but I'd like to have a valid source URL before the update of my Fedora / RHEL packages.

**Comment by marc-hb** [comment]
Should be fixed now, sorry for the delay.

**Comment by mengdonglin** [comment]
@marc-hb Thank you!

**Comment by mrhpearson** [comment]
Just as an FYI update - the Debian method has been updated to use the tarballs now; and the 2.2.2 package is prepared for release (hopefully goof free).
Big thanks to @vincentbernat for helping me with the transition (and some other improvements)

**Pull request merged**
