### PR TITLE
Fix/links

### PR DESCRIPTION
**Pull request by plbossart**
Make it straightforward to install baseline for Intel platforms

### CODE REVIEW

**Comment by lgirdwood** [comment]
@xiulipan fyi, what's your ETA for starting work on this and adding the missing features ?

**Comment by xiulipan** [comment]
@lgirdwood I will start to do some test now and to see if there is any issues.

**Comment by lgirdwood** [comment]
@xiulipan great thanks - @perexg fyi, I guess you will be an initial user of this script (it may also need your inputs though to correctly build an rpm).

**Comment by perexg** [comment]
To tell you truth. I don't get the idea behind the script and the symlinks removal. I'm actually using the previous version with symlinks. It's simplier to do 'cp -ar' then verify some custom script for each release. The previous version was acceptable for me.

**Comment by perexg** [comment]
I would use the script only for users who wants to remove the old firmware and copy the firmware to the proper location (which we do in our package scripts).

This is my .rpm for the full tree (with symlinks): https://src.fedoraproject.org/rpms/alsa-sof-firmware/blob/master/f/alsa-sof-firmware.spec

As you see, 'cp -ar'  on line 42 does the whole job.

**Comment by plbossart** [comment]
@perexg The hard-coded symlinks in the git tree are really not good IMO.

Take the example of the Up2 board or Chromebooks, for those we'd need the firmware signed with the community key. So we should have a script that defined what platform you want to install on and create the symlinks during install.

Fedora will not work on Up2 and Chromebooks...

**Pull request merged**
